name: TeamsAndMore
version: 1.0.1
main: main.io.github.itshaithamn.teamsandmore.Main
api-version: 1.21

softdepend:
  - ProtocolLib
  - DiscordSRV
  - LuckPerms

commands:
  team:
    description: root command
    aliases:
      - teamsandmore


permissions:
  teamsandmore.admin:
    description: Admin for tests
    default: false